name: Languages Metrics

on:
  push:
   branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ github.token }}
          filename: .github/metrics/languages_metrics.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            dockerfile, makefile, cmake
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          commits_authoring: Dmitriy Tikhomirov, uroborosq, uroborosq@ya.ru, uroborosq@gmail.com, UroborosQ, Tikhomirov Dmitriy
