
name: WakaTime Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          filename: .github/metrics/wakatime_metrics.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, editors, languages-graphs, os-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
